name: Fetch Recent Activity

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  fetch-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Recent Activity
        run: |
          curl -sSLf https://api.github.com/users/Asepharyana71/events/public \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/json" \
            | jq '.[] | .created_at, .type, .repo.name' > activity.json

      - name: Generate README
        run: |
          echo "## Recent Activity" > README.md
          echo "" >> README.md
          cat activity.json >> README.md

      - name: Commit changes
        run: |
          git config --local user.name "Asep haryana"
          git config --local user.email "exceednethunter@gmail.com"
          git add README.md
          git commit -m "Update README with recent activity" || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
